import type { RelayKanbanCard, RelayKanbanColumnId } from "@/lib/relay/relay-work-center-model";

/** Beispiel-Vorgänge — zeigen Vielfalt, wenn die Praxis noch wenig Live-Daten hat. */
export const RELAY_KANBAN_EXAMPLES: RelayKanbanCard[] = [
  {
    id: "example-decision-recall",
    href: "/my-tasks/new",
    typeLabel: "Recall",
    typeCode: "R",
    title: "Recall Q2 — 12 Patienten bestätigen",
    metaLine: "Bearbeitet von ZMP · Ärztliche Entscheidung",
    dateLabel: "Freitag",
    actionLabel: "Entscheiden",
    assigneeInitials: "ZM",
    assigneeColor: "#0f766e",
    commentCount: 0,
    priority: "normal",
    isGhost: true,
    columnId: "decision",
  },
  {
    id: "example-decision-patient",
    href: "/inbox",
    typeLabel: "Patientenanfrage",
    typeCode: "P",
    title: "Schwellung nach Implantat — Rückruf",
    metaLine: "Patient wartet · Empfang",
    dateLabel: "vor 3 Std.",
    actionLabel: "Antworten",
    assigneeInitials: "EM",
    assigneeColor: "#2f80ed",
    commentCount: 0,
    priority: "important",
    isGhost: true,
    columnId: "decision",
  },
  {
    id: "example-progress-lab",
    href: "/my-tasks/new",
    typeLabel: "Labor",
    typeCode: "T",
    title: "Krone Zahn 16 — Farbnahme Termin",
    metaLine: "In Bearbeitung · ZFA Anna",
    dateLabel: "Heute",
    actionLabel: "Bearbeiten",
    assigneeInitials: "ZA",
    assigneeColor: "#64748b",
    commentCount: 0,
    priority: "normal",
    isGhost: true,
    columnId: "in_progress",
  },
  {
    id: "example-progress-handoff",
    href: "/relay?area=nachrichten",
    typeLabel: "Übergabe",
    typeCode: "U",
    title: "OP-Nachsorge — Übergabe an Spätdienst",
    metaLine: "Team · Interne Nachricht",
    dateLabel: "gestern",
    actionLabel: "Öffnen",
    assigneeInitials: "TE",
    assigneeColor: "#1a2b4a",
    commentCount: 0,
    priority: "normal",
    isGhost: true,
    columnId: "in_progress",
  },
  {
    id: "example-done-hygiene",
    href: "/my-tasks/new",
    typeLabel: "Routine",
    typeCode: "R",
    title: "Hygiene-Checkliste Woche 22",
    metaLine: "Erledigt · Praxisleitung",
    dateLabel: "gestern",
    actionLabel: "Öffnen",
    assigneeInitials: "PL",
    assigneeColor: "#334155",
    commentCount: 0,
    priority: "normal",
    isGhost: true,
    columnId: "done",
  },
  {
    id: "example-done-faq",
    href: "/journal",
    typeLabel: "Care Center",
    typeCode: "J",
    title: "FAQ „Schmerzen nach OP“ veröffentlicht",
    metaLine: "Erledigt · ZFA Maria",
    dateLabel: "Mo.",
    actionLabel: "Ansehen",
    assigneeInitials: "ZM",
    assigneeColor: "#2f80ed",
    commentCount: 0,
    priority: "normal",
    isGhost: true,
    columnId: "done",
  },
];

export function examplesForKanbanColumn(columnId: RelayKanbanColumnId): RelayKanbanCard[] {
  return RELAY_KANBAN_EXAMPLES.filter((c) => c.columnId === columnId);
}
