export const PROFILE_LIMITS = {
  first_name: 30,
  last_name: 30,
  title: 30,
  founding_year: 4,
  vita_markdown: 2000,
  specialization_custom: 60,
  service_name: 50,
  service_note: 30,
  practice_name: 50,
  practice_address: 180,
  practice_employment_status: 80,
  practice_phone: 30,
  practice_email: 80,
  practice_website: 100,
  practice_hours: 100,
  MAX_VISIBLE_SPECIALIZATIONS: 6,
  MAX_VISIBLE_SERVICES: 12,
} as const;
